$(document).ready(function(){var navbarShrink=function(){const navbarCollapsible=document.body.querySelector('#mainNav');if(!navbarCollapsible){return;}
if(window.scrollY===0){navbarCollapsible.classList.remove('navbar-shrink')}else{navbarCollapsible.classList.add('navbar-shrink')}};navbarShrink();document.addEventListener('scroll',navbarShrink);const navbarToggler=document.body.querySelector('.navbar-toggler');const responsiveNavItems=[].slice.call(document.querySelectorAll('#navbarResponsive .nav-link'));responsiveNavItems.map(function(responsiveNavItem){responsiveNavItem.addEventListener('click',()=>{if(window.getComputedStyle(navbarToggler).display!=='none'){navbarToggler.click();}});});var totalcost=Number(0);$('[data-quantity="plus"]').click(function(e){var hdPrice=$('#hdPrice').val();$('.invalid-feedback').hide();e.preventDefault();fieldName=$(this).attr('data-field');countryName=$('input[name='+fieldName+']').attr('data-country');var currentVal=parseInt($('input[name='+fieldName+']').val());var value=$('input[name='+fieldName+']').val();var max=$('input[name='+fieldName+']').attr('data-max');if((value!=='')&&(value.indexOf('.')===-1)){$('input[name='+fieldName+']').val(Math.max(Math.min(value,max),0));}
if(!isNaN(currentVal)&&currentVal<max){$('input[name='+fieldName+']').val(currentVal+1);var updatedVal=currentVal+1;totalcost=Number(totalcost)+1;$('.total-cost').text((totalcost*hdPrice).toFixed(2));}});$('[data-quantity="minus"]').click(function(e){var hdPrice=$('#hdPrice').val();$('.invalid-feedback').hide();e.preventDefault();fieldName=$(this).attr('data-field');countryName=$('input[name='+fieldName+']').attr('data-country');var currentVal=parseInt($('input[name='+fieldName+']').val());var value=$('input[name='+fieldName+']').val();var max=$('input[name='+fieldName+']').attr('max');if(!isNaN(currentVal)&&currentVal>0){$('input[name='+fieldName+']').val(currentVal-1);var updatedVal=currentVal-1;totalcost=Number(totalcost)-1;$('.total-cost').text((totalcost*hdPrice).toFixed(2));}else{$('input[name='+fieldName+']').val(0);}});$('.input-group-field').blur(function(){var hdPrice=$('#hdPrice').val();$('.invalid-feedback').hide();fieldName=$(this).attr('name');if(!this.value){$(this).val('0');}
var updatedVal=this.value;totalcost=Number(updatedVal);$('.total-cost').text((totalcost*hdPrice).toFixed(3));});$('.input-group-field').on('input',function(){var value=$(this).val();var max=$(this).attr('data-max');if((value!=='')&&(value.indexOf('.')===-1)){$(this).val(Math.max(Math.min(value,max),0));}});if($(window).width()<=991){$('body').removeAttr('style');$('.navbar').removeAttr('style');}else{if($('.peekaboo').is(":visible")){var pkbH=$('.peekaboo').outerHeight();$('body').css('padding-top',pkbH);$('.navbar').css('margin-top',pkbH);}}
checkPkb();$(window).resize(function(){if($(window).width()<=991){$('body').removeAttr('style');$('.navbar').removeAttr('style');}else{if($('.peekaboo').is(":visible")){var pkbH=$('.peekaboo').outerHeight();$('body').css('padding-top',pkbH);$('.navbar').css('margin-top',pkbH);}}});$('.close-icon').click(function(){$(this).parents('.peekaboo').slideToggle(300);$('body').removeAttr('style');$('.navbar').removeAttr('style');})
if($('.vid-timelapse').length>0){var vid=document.getElementById("vid-timelapse");vid.playbackRate=8.0;}
window.onscroll=function(){scrollFunction()};if($('[data-bs-spy="scroll"]').length>0){var scrollSpy=new bootstrap.ScrollSpy(document.body,{target:'#navbar-nav',offset:140})}
hotfixScrollSpy();window.scrollBy(0,1);if($('.countdown-holder').length>0){var d=new Date("2021-08-14T12:00:00.000+08:00");var zz=d.toLocaleString('en-US',{timeZone:'America/New_York'});console.log(zz);var countDownDate=new Date(zz).getTime();var x=setInterval(function(){var nowEst=new Date().toLocaleString('en-US',{timeZone:'America/New_York'});var now=new Date(nowEst).getTime();var distance=countDownDate-now;var days=Math.floor(distance/(1000*60*60*24));var hours=Math.floor((distance%(1000*60*60*24))/(1000*60*60));var minutes=Math.floor((distance%(1000*60*60))/(1000*60));var seconds=Math.floor((distance%(1000*60))/1000);$('#days').text(days);$('#hours').text(hours);$('#minutes').text(minutes);$('#seconds').text(seconds);if(distance<0){clearInterval(x);$(".countdown-holder").html("<h1>EXPIRED</h1>");}},1000);}
if(window.location.href.indexOf('#tnc')!=-1){$('#staticBackdrop').modal('show');}
if($('#renameModal').length>0){var exampleModal=document.getElementById('renameModal')
exampleModal.addEventListener('show.bs.modal',function(event){var button=event.relatedTarget
var recipient=button.getAttribute('data-bs-whatever')
var modalTitle=exampleModal.querySelector('.modal-title')
var modalBodyInput=exampleModal.querySelector('.modal-body input')
modalTitle.textContent='Rename Mummy for '+recipient
modalBodyInput.value=recipient})}});function hotfixScrollSpy(){var dataSpyList=[].slice.call(document.querySelectorAll('[data-bs-spy="scroll"]'))
let curScroll=getCurrentScroll();dataSpyList.forEach(function(dataSpyEl){let offsets=bootstrap.ScrollSpy.getInstance(dataSpyEl)['_offsets'];for(let i=0;i<offsets.length;i++){offsets[i]+=curScroll;}})}
function getCurrentScroll(){return window.pageYOffset||document.documentElement.scrollTop;}
function scrollFunction(){if(document.body.scrollTop>400||document.documentElement.scrollTop>400){$("#back-top").fadeIn(300);}else{$("#back-top").fadeOut(300);}}
function topFunction(){document.body.scrollTop=0;document.documentElement.scrollTop=0;}
function checkPkb(){if($(window).width()<=991){$('body').removeAttr('style');$('.navbar').removeAttr('style');}else{if($('.peekaboo').is(":visible")){var pkbH=$('.peekaboo').outerHeight();$('body').css('padding-top',pkbH);$('.navbar').css('margin-top',pkbH);}}}
function copywallet(element,z){var $temp=$("<input>");$("body").append($temp);$temp.val($(element).text()).select();document.execCommand("copy");$temp.remove();$(z).attr('title','Copied');alert("Copied");}